version: '3'
services:
  app:
    build: .
    image: keboola/dbt-transformation
    volumes:
      - ./:/code
      - ./data:/data

  app-tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    command: composer ci
